# NumPy

In [1]:
import numpy as np


# `numpy.ndarray` 클래스 속성들(properties)

In [2]:
# 2차원 배열(2-dimensional array)
arr=np.ones(shape=(2,3)) # 모든 원소가 1인 배열     dtype=(int)

In [3]:
arr # 1.0

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr.shape   # shape속성: 배열의 각 축(axis)을 따라서 있는 원소 개수들의 튜플(tuple)

(2, 3)

In [5]:
arr.size    # size속성: 배열의 모든 원소 개수

6

In [6]:
arr.ndim  # ndim속성: 배열의 차원 개수. 축(axis)의 개수.

2

In [7]:
arr.dtype   # dtype속성: 배열 원소의 데이터 타입(data type)

dtype('float64')

In [8]:
# 1차원 배열(1-dimensional array)
arr = np.arange(10)
print(arr)
print('shape',arr.shape)
print('shape',arr.size)
print('shape',arr.ndim)
print('shape',arr.dtype)
arr

[0 1 2 3 4 5 6 7 8 9]
shape (10,)
shape 10
shape 1
shape int64


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 3차원 배열(3-dimensional array)
arr=np.arange(1,25).reshape((2,3,4)) #  z y x

In [10]:
print(arr)
# arr

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
print('shape:',arr.shape)
print('shape',arr.size)
print('shape',arr.ndim)
print('shape',arr.dtype)


shape: (2, 3, 4)
shape 24
shape 3
shape int64


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [12]:
print(arr)  # 3d array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [13]:
print(arr[0])  # 2d array 인덱스를뽑았다 축하나 탈락

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
print(arr[0][0]) # 1d array

[1 2 3 4]


In [15]:
print(arr[0,0]) # numpy 배열에서만

[1 2 3 4]


In [16]:
print(arr[0,0,0]) # 값(int) >> scalar

1


In [17]:
print(arr[0][0][0])

1


*   Python list 인덱스 사용방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용방법:
    *   `array[i][j][k]...`
    *   `array[i, j, k, ...]`    

# Slicing

배열을 잘라서 새로운 배열을 만듦.

## 1d array의 slicing

In [18]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(arr[1:5])

[1 2 3 4]


In [20]:
print(arr[:3]) # 시작 인덱스 0은 생략이 가능하다

[0 1 2]


In [21]:
print(arr[-3:]) # 배열의 끝까지 자를 때에는 마지막 인덱스를 생략할 수 있다.

[7 8 9]


In [22]:
print(arr[0:1]) #slicing - > 결과는 배열(ndarray)
print(arr[0]) # indexing - > 결과는 원소

[0]
0


## 2d array의 slicing

In [23]:
arr= np.arange(1,21).reshape((4,5)) # y x
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
print(arr[:2]) # 2차원배열이니까 그리고 배열하나선택했으니까

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
print(arr[:2,:]) # 위와 결과값이 동일

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [26]:
print(arr[:2,:3]) #

[[1 2 3]
 [6 7 8]]


In [27]:
print(arr[1:3,1:4])

[[ 7  8  9]
 [12 13 14]]


In [28]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
print(arr[:3][:2]) #print(arr[:3][:2,:2]) ㅇㅋ ㅇㅈ slicing에서는 콤마를 애용하는게 좋겠다

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
print(arr[:3,:2])

[[ 1  2]
 [ 6  7]
 [11 12]]


## 3d array의 slicing

In [31]:
arr=np.arange(60).reshape((3,4,5))

In [32]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [33]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [34]:
print(arr[:2,:,:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [35]:
print(arr[:2,:2]) # 축을벗기려면 대괄호를닫아야 축이안벗겨지는데? 원래안벗겨지는구나

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [36]:
print(arr[:2,:2,:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [37]:
print(arr[:2][:1]) # 3차원부터는 사용처가있다

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [38]:
print(arr[:2,:2,:2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [39]:
# print(arr[:2][:2][:2])

In [40]:
print(arr[0]) # 축벗기는건 indexing이다

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [41]:
print(arr[:1,:,:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [42]:
print(arr[0,:,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# 배열 모양(shape) 변경

*   `reshape()`
*   `ravel()`
*   `flatten()`
*   `np.newaxis` 속성

In [43]:
# ravel vs flatten
# n차원을 1차원으로

## reshape

In [44]:
arr_1d=np.arange(12) #1차원
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
# arr_1d를 (4,3) shape의 2d array로 변환
arr_2d=arr_1d.reshape((4,3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [46]:
# reshape 메서드에 아규먼트를 전달할 때, 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d=arr_1d.reshape((4,-1))# (4,3)
print(arr_2d) # 인덱스 마지막  (-1,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
arr_2d=arr_1d.reshape((-1,4)) #(3,4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
arr_1d=np.arange(24)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [49]:
# arr_1d를 (2,3,4) 모양의 3d array로 변환  -1의 활용법
arr_3d=arr_1d.reshape((2,3,4))#(2,3,-1)
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
arr_3d=arr_1d.reshape((4,3,-1))#(2,3,-1)
print(arr_3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [51]:
arr_3d=arr_1d.reshape((-1,3,4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## ravel vs flatten

* ravel
  * n차원 배열을 **1차원 배열로 변환한 "뷰(view)"를 리턴.**
  * **새로운 1차원 배열을 만드는 것이 아니라**, 원본 배열의 모양을 1차원처럼 보여줄 뿐.
  * 리턴된 1차원 배열에서 **원소를 변경하면, 원본 배열도 변경됨!**
* flatten
  * n차원 배열을 **1차원 배열로 변환한 "복사본"을 리턴.**
  * **원본 배열과는 별개의** 새로운 1차원 배열을 메모리에 만들어서 리턴.  
  * 리턴된 1차원 배열의 원소를 **변경하는 것은 원본 배열에 영향을 주지 않음!**

In [52]:
arr_2d=np.arange(12).reshape((3,4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
flattened=arr_2d.flatten() # 2d >> 1d

In [54]:
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# 복사본
flattened[0]=123
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [56]:
print(arr_2d) # 원본 2d array는 변경되지 않았다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
raveled=arr_2d.ravel() # 2d >> 1d

In [58]:
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
raveled[0]=123
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [60]:
print(arr_2d) # 원본 2d array는 변경 되었다.

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [61]:
arr=np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [62]:
arr.shape

(6,)

In [63]:
result = arr[np.newaxis, :]   # [새 축 추가 , 모든원소]
print(result)

[[0 1 2 3 4 5]]


In [64]:
result.shape

(1, 6)

In [65]:
print(arr.reshape(1,-1))

[[0 1 2 3 4 5]]


In [66]:
result= arr[:,np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [67]:
result.shape

(6, 1)

In [68]:
print(arr.reshape(-1,1)) #np.newaxis는 reshape으로 대체가능

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


# 배열 합치기(concatenate)

*   `np.concatenate([array1,array2,...],axis=0)`(axis기본값=0, or 1)
    :특정 축(axis) 방향으로 배열 이어붙이기.

*   `np.r_[array1,array2]`: 행들을 이어붙이기. axis=0 방향으로 이어붙이기.(concatenate기준)
*   `np.c_[array1,array2]`: 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.(concatenate기준)

In [69]:
# (2,3) shape의 2d array
arr1 = np.arange(6).reshape(2,3)
print(arr1)

[[0 1 2]
 [3 4 5]]


In [70]:
# (1,3) shape의 2d array
arr2 = np.array([[10,20,30]])
print(arr2)

[[10 20 30]]


In [71]:
# (2, 1) shape의 2d array
arr3 = np.array([[11],[12]])
print(arr3)

[[11]
 [12]]


In [72]:
result = np.concatenate([arr1,arr2]) #axis=0 은 기본이다
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


In [73]:
result = np.concatenate([arr1,arr3],axis=1) #axis=0 은 기본이다 2차원이상에서 다가능
print(result)

[[ 0  1  2 11]
 [ 3  4  5 12]]


In [74]:
np.r_[arr1,arr2] # 2차원만 가능하다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [75]:
np.c_[arr1,arr3]

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 12]])

In [76]:
# arr1 =np.arange(6).reshape(2,3)
# print(arr1)

In [77]:
# arr2=np.array([10,20,30])
# print(arr2)

In [78]:
# np.concatenate([arr1,arr2],axis=0)
# ValueError 발생. 차원이 다르면 concatenate가 이어붙이기가 되지 않음.

# Broadcasting

*   numpy.ndarray의 연산(+, -, *, /, ==, !=, >, <, ...)은 같은 인덱스(위치)의 원소(element-wise)들끼리 연산이 수행됨.
*   서로 모양(shape)이 다른 배열끼리도 element-wise 연산이 가능한 경우가 있음 >> broadcast
*   broadcasting이 가능한 경우
    *   누락되었거나 길이가 1인 차원에 대해서 broadcasting이 수행.
    *   이어지는 차원의 축의 길이가 같은 경우에 broadcasting이 가능.   

## ndarray와 scalar의 연산

항상 연산이 가능(항상 broadcast가 가능). 스칼라를 배열의 각 원소마다 연산 수행.

In [79]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [80]:
print(a + 10)

[11 12 13]


## 2d array와 2d array의 broadcast

In [81]:
a=np.arange(1,7).reshape((2,3))
print(a)  #shape: (2,3)

[[1 2 3]
 [4 5 6]]


In [83]:
b=np.array([[7,8,9]]) #shape: (1,3)
print(b)

[[7 8 9]]


In [84]:
print(a+b)

[[ 8 10 12]
 [11 13 15]]


In [85]:
c=np.array([[11],[12]]) #shape: (2,1)
print(c)

[[11]
 [12]]


In [86]:
print(a+c)

[[12 13 14]
 [16 17 18]]


## 2d array와 1d array의 broadcast

In [87]:
print(a)

[[1 2 3]
 [4 5 6]]


In [88]:
d=np.array([7,8,9]) #shape: (3, )
print(d)


[7 8 9]


In [90]:
print(a+d)

[[ 8 10 12]
 [11 13 15]]


In [91]:
e=np.array([7,8]) #shape: (2, )
print(e)

[7 8]


In [92]:
# print(a+e) 축의 길이가 다르다
# ValueError 발생: (2,3)과 (2, ) 모양의 배열들은 브로드캐스트가 불가능.

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## broadcast 활용

*   표준화(standardization): 평균이 0이 되고 표준편차가 1이 되도록 값들을 변환.
>   $$z = \dfrac{x - \mu}{\sigma}$$ (mu=mean)(sigma=std)
*   정규화(normalization): 최솟값이 0이 되고 최댓값이 1이 되도록 값들을 변환.
>   $$x_{norm} = \dfrac{x - x_{min}}{x_{max} - x_{min}}$$

### 1차원 배열 표준화

In [93]:
x = np.arange(1,6)
print(x)

[1 2 3 4 5]


In [95]:
mu= x.mean() # 평균
print(mu)

3.0


In [96]:
sigma=x.std() # 표준편차(standard deviation)
print(sigma)

1.4142135623730951


In [97]:
x_scaled = (x - mu) / sigma
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [99]:
print(x_scaled.mean())
print(x_scaled.std())

0.0
0.9999999999999999


### 1차원 배열 **정규화**

In [100]:
print(x)

[1 2 3 4 5]


In [101]:
x_norm = (x-x.min()) /(x.max()-x.min())
print(x_norm)

[0.   0.25 0.5  0.75 1.  ]


### 2차원 배열에서의 표준화

In [122]:
x  =np.arange(1,13).reshape((4,3)) # 3가지
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
mu = x.mean() # 파라미터 axis=None인 경우, 모든 원소(스칼라)들의 평균  1 방법
print(mu)

6.5


In [104]:
sigma= x.std() # 파라미터 axis=None인 경우, 모든 원소(스칼라)들의 평균
print(sigma)

3.452052529534663


In [105]:
x_scaled = (x-mu)/sigma
print(x_scaled)

[[-1.59325501 -1.30357228 -1.01388955]
 [-0.72420682 -0.43452409 -0.14484136]
 [ 0.14484136  0.43452409  0.72420682]
 [ 1.01388955  1.30357228  1.59325501]]


In [106]:
# axis=0 축 방향으로 평균을 계산  2 방법
mu = x.mean(axis=0)           #keepdims=True
print(mu)  # mu shape:(3, )   (1,3)

[5.5 6.5 7.5]


In [107]:
# axis=0 축 방향으로 표준편차들을 계산
sigma= x.std(axis=0)
print(sigma)  # sigma shape(3, )

[3.35410197 3.35410197 3.35410197]


In [108]:
# axis=0 축 방향으로 값들을 표준화
x_scaled = (x - mu)/sigma
print(x_scaled)

[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]


In [115]:
# axis=1 축 방향으로 평균들을 계산 3 방법
mu=x.mean(axis=1,keepdims=True)
print(mu) #shape(4, ) >> shape(4,1)

[[ 2.]
 [ 5.]
 [ 8.]
 [11.]]


In [113]:
# mu.reshape((4,1))

array([[ 2.],
       [ 5.],
       [ 8.],
       [11.]])

In [116]:
x-mu

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [117]:
# axis=1 축 방향으로 표준편차들을 계산
sigma=x.std(axis=1,keepdims=True)
print(sigma) #shape(4,1)

[[0.81649658]
 [0.81649658]
 [0.81649658]
 [0.81649658]]


In [119]:
x_scaled=(x-mu)/sigma
print(x_scaled)

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]


In [123]:
# 2차원 배열의 정규화 axis=0,1,X
x_norm=(x-x.min())/(x.max()-x.min())
x_norm
# x_norm0=
# x_norm1=

array([[0.        , 0.09090909, 0.18181818],
       [0.27272727, 0.36363636, 0.45454545],
       [0.54545455, 0.63636364, 0.72727273],
       [0.81818182, 0.90909091, 1.        ]])

In [124]:
x_norm0=(x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
x_norm0

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

In [126]:
x_norm1=(x-x.min(keepdims=True,axis=1))/(x.max(keepdims=True,axis=1)-x.min(keepdims=True,axis=1))
x_norm1

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])