# 데이터 분석 패키지(라이브러리)(기능들의모음)

*   NumPy: 다차원 배열을 쉽게 사용할 수 있도록 만들어진 패키지. 머신러닝에서 중요하게 사용됨.
*   pandas: 시리즈(Series)와 데이터프레임(DataFrame)을 기본으로 사용해서 데이터 분석에 필요한 기능들을 가지고 있는 패키지.
*   matplotlib, seaborn: 데이터 시각화(그래프) 패키지.
*   scikit-learn: 머신러닝(Machine Learing) 패키지.
*   keras: 딥러닝(Deep Learning) 패키지.

In [7]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
import sklearn # scikit-learn 패키지
import keras

In [8]:
print('numpy version= ', np.__version__)
print('pandas version= ', pd.__version__)
print('matplotlib version =',matplotlib.__version__)
print('seaborn version =',sns.__version__)
print('sklearn version =',sklearn.__version__)
print('keras version =',keras.__version__)

numpy version=  2.0.2
pandas version=  2.2.2
matplotlib version = 3.10.0
seaborn version = 0.13.2
sklearn version = 1.6.1
keras version = 3.10.0


# Python `list` 클래스

*   여러개의 값들을 저장할 수 있는 데이터 타입.
*   인덱스를 기반으로 한 데이터 타입.
    *   indexing: 인덱스를 사용해서 리스트의 특정 위치의 값을 참조.(예) `list[0]`
    *   slicing: [start,end) 인덱스 범위의 리스트를 잘라냄. (예) `list[0:5]`
*   산술 연산
    *   `list + list`: concatenate. 리스트 이어붙이기.
    *   `list * int, int * list`: replicate. 리스트의 원소들을 정수만큼 복사.

In [9]:
numbers1=[1,2,3]
numbers2=[11,22,33]


In [10]:
print(numbers1) #대괄호 쉼표구분

[1, 2, 3]


In [11]:
numbers2

[11, 22, 33]

In [12]:
# indexing
print(numbers1[0]) #리스트의 첫번째 원소
print(numbers1[-1]) #리스트의 마지막 원소


1
3


In [13]:
#slicing
print(numbers2[0:2]) # 리스트에서 첫 2개 원소들을 잘라내기
print(numbers2[-2:]) # 리스트에서 마지막 2개 원소들을 잘라내기

[11, 22]
[22, 33]


In [14]:
numbers1 +numbers2

[1, 2, 3, 11, 22, 33]

In [15]:
numbers1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [16]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 덧셈 --> [12,24,36]
asd=[x+y for x,y in zip(numbers1, numbers2)]
print(asd)

[12, 24, 36]


In [17]:
# numbers1의 모든 원소에 3을 곱함
[x*3 for x in numbers1]

[3, 6, 9]

In [18]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 곱셈 --> [11,44,99]
[x*y for x,y in zip(numbers1,numbers2)]

[11, 44, 99]

# NumPy(Numerical Python)

*   다차원배열(n-dimensional array)을 쉽고 빠르게 연산(`+,-,*,/,...`)하기 위한 패키지.
*   numpy 패키지의 대부분의 기능들(연산자, 함수, 메서드 등)은 반복문의 기능을 가지고 있음.
    *   같은 인덱스의 원소들끼리(element-wise) 연산하는 기능을 가지고 있음.
*   `numpy.ndarray` 클래스: numpy 패키지의 가장 기본이 되는 클래스.
    

In [25]:
num_array1 = np.array([1,2,3,4,5])

In [26]:
type(num_array1)

numpy.ndarray

In [27]:
print(num_array1) #  ,가없다 ' ' 으로출력  ndarray클래스의 __str__() 메서드가 리턴하는 문자열을 출력

[1 2 3 4 5]


In [28]:
num_array1    # ndarray 클래스의 __repr__() 메서드가 리턴하는 문자열을 출력

array([1, 2, 3, 4, 5])

In [29]:
num_array2 =np.array([10,20,30,40,50])

In [30]:
# element-wise(같은 인덱스의 원소들끼리) 연산
print(num_array1+num_array2) #
print(num_array1-num_array2)
print(num_array1*num_array2)
print(num_array1*3)
print(num_array1/num_array2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[ 3  6  9 12 15]
[0.1 0.1 0.1 0.1 0.1]


# `np.ndarry` 클래스의 속성들(attributes)

In [31]:
print(num_array1)
print('ndim= ',num_array1.ndim) # number of dimension (차원의 개수)
print('size = ', num_array1.size) # 배열의 크기(모든 원소의 개수)
print('shape = ', num_array1.shape) # 배열의 모양(배열의 각 차원의 원소 개수들로 이루어진 튜플)
print('dtype = ', num_array1.dtype) # data type(배열 원소의 데이터 타입)

[1 2 3 4 5]
ndim=  1
size =  5
shape =  (5,)
dtype =  int64


*   Python의 숫자 타입
    * 정수: int
    * 실수: float
*   NumPy 숫자 타입
    * 정수: int8, int16, int32, int64, ...
    * 실수: float16, float32, float64, ...

In [32]:
# 2차원 배열
array = np.array([[1,2,3],
                [4,5,6]])

In [33]:
print(array)

[[1 2 3]
 [4 5 6]]


In [34]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print('ndim =',array.ndim)
print('size =',array.size)
print('shape =',array.shape)
print('dtype =',array.dtype)

ndim = 2
size = 6
shape = (2, 3)
dtype = int64


# `np.ndarray` 객체 생성 함수

## `np.array(object)`

*   object를 ndarray로 변환해서 리턴.
*   object: 배열과 비슷한 객체들. list, tuple, ndarray, ...


In [36]:
# 0 이상 10 미만의 정수들로 이루어진 ndarray(배열)만들기
numbers= np.array([x for x in range(0,10)])
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


## `np.arange(start,end,step)`

*   range를 사용해서 array(배열)을 만들어 주는 함수.
*   파이썬 `range(start, end,step)` 함수 사용법과 같다.
*   1차원 배열(ndarray)를 생성.


In [37]:
# 0 이상 10 미만의 정수들로 이루어진 ndarray(배열)만들기
numbers=np.arange(10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 0 이상 10미만의 짝수들로만 이루어진 배열
evens= np.arange(0,10,2)
print(evens)

[0 2 4 6 8]


## reshape

*   `np.reshape(array, newshape)` 함수(function)
*   `np.ndarray.reshape(newshape)` 메서드(method)


In [70]:
array = np.arange(12)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
# reshape 함수
array2= np.reshape(array, (3,4))#모양은 tuple로
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
# reshape 메서드
print(array)
array3=array.reshape((4,3))
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
# 함수(메서드) 연쇄 호출
array =np.arange(15).reshape((3,5))
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 난수 배열

### `np.random.rand(d0, d1, d2, d3, ...)`

*   [0,1) 범위의 **균등분포(uniform distribution)**를 따르는 난수들의 배열을 생성.
*   아규먼트 (d0, d1, ...)들은 각 차원의 원소 개수.


In [43]:
array=np.random.rand(5)
print(array)

[0.09399316 0.01828678 0.06918936 0.99869963 0.50734389]


In [44]:
array=np.random.rand(3,4)
print(array)

[[0.7660532  0.90269332 0.44492875 0.81321548]
 [0.96536492 0.51065419 0.96259345 0.63675709]
 [0.5750563  0.37605987 0.89859722 0.59156301]]


### ` np.random.randn(d0, d1, d2, ...)`

*   평균이 0이고 표준편차가 1인 **표준 정규 분포(standard normal distridution)**를 따르는 난수들의 배열을 생성.
*   아규먼트(d0, d1, d2, ...)는 각 차원의 원소 개수.

In [45]:
array =np.random.randn(10)
print(array)

[-1.92867329 -2.88030669 -0.88178353  1.25156689 -0.65226939  0.85668381
  0.61036608  0.3308504   1.41811569  1.71391756]


In [46]:
array=np.random.randn(3,5)
print(array)

[[ 1.68240999  0.51076758  1.22816861  1.79927868  4.058637  ]
 [-0.941751    0.97269354  0.35072292 -0.71343501 -0.79680397]
 [ 1.70655978  0.27806464  1.25891034  1.75404801  2.02207716]]


### `np.random.randint(low, high, size, dtype)`

*   [low, high) 범위의 정수 난수들을 원소로 하는 배열을 생성.
*   파라미터 size: ndarray의 **shape**을 정수 또는 튜플로 전달. (1차원은 원소의개수)         (파라미터 size는 shape이다)
*   파라미터 dtype: int8, int16, int32, int64,...

In [47]:
array=np.random.randint(0,10,size=5)  #파라미터 size에 정수를 전달 >> 1차원 배열
print(array)

[8 6 2 1 5]


In [48]:
array=np.random.randint(0,10,size=(5,))  # shape이 (5, )인 1차원 배열
print(array)

[8 5 9 0 9]


In [49]:
array= np.random.randint(0,10,size=(4,5))  #shape이 (4,5)인 2차원 배열
print(array)

[[1 6 8 8 1]
 [4 9 4 6 8]
 [4 9 6 2 0]
 [7 4 3 7 2]]


# 통계 함수/메서드


*   합계 평균 분산 최대 최소 표준편차 중앙값(X함수만있다), ...
*   함수: `np.function_name(ndarray)`
*   메서드: `np.ndarray.method_name()`

In [50]:
array =np.random.randint(100,size=10)   # 0 이상 100 미만 10개의 정수 난수를 갖는 배열
print(array)

[69 49 75 88 89  5 63 71 75 79]


In [51]:
print('합계 : ',np.sum(array), array.sum()) # 배열을 아규먼트로 /// 배열안에서 합계

합계 :  663 663


In [52]:
print('평균 : ',np.mean(array), array.mean()) #numpy의 함수 /// 만든 객체의 기능

평균 :  66.3 66.3


In [53]:
print('분산 : ',np.var(array), array.var())

분산 :  539.6099999999999 539.6099999999999


In [54]:
print('표준편차 : ',np.std(array), array.std())

표준편차 :  23.22950709765491 23.22950709765491


In [55]:
print('최댓값 : ',np.max(array), array.max())

최댓값 :  89 89


In [56]:
print('최솟값 : ',np.min(array),array.min())

최솟값 :  5 5


In [57]:
print('중앙값 : ',np.median(array)) # 중앙값 메서드는 없다

중앙값 :  73.0


## 2차원 배열에서의 통계 함수/메서드

In [76]:
np.random.seed(42) # seed가 같으면 값 일정하다 /// 실행할 때마다 같은 난수들을 생성하기 위해서.
array=np.random.randint(10,size=(5,4))
print(array)   # 축  axis 세로 0 가로 1

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]
 [1 7 5 1]]


In [77]:
np.sum(array) # 2차원 배열의 모든 원소들의 합계
# print(np.sum(array))

np.int64(96)

In [78]:
print(np.sum(array))

96


In [79]:
array.sum()

np.int64(96)

In [80]:
np.sum(array, axis=0) #세로길이합 (axis=0 축을 따라서 계싼한 원소들의 합계)

array([27, 25, 22, 22])

In [81]:
array.sum(axis=0)

array([27, 25, 22, 22])

In [82]:
np.sum(array,axis=1) #가로길이합 (axis=1 축을 따라서 계싼한 원소들의 합계)

array([20, 23, 21, 18, 14])

In [83]:
array.sum(axis=1)

array([20, 23, 21, 18, 14])

In [86]:
array.sum(axis=0,keepdims=True) # 2차원 배열 세로길이합 (1,4)shape  False는 기본 axis sum과 동일한 결과가나옴

array([[27, 25, 22, 22]])

In [67]:
array.sum(axis=1,keepdims=True) # 2차원 배열 가로길이합 (5,1)shape

array([[20],
       [23],
       [21],
       [18],
       [14]])