In [1]:
import numpy as np
import pandas as pd


# Series 인덱스

## 단일 계층 인덱스

In [175]:
s= pd.Series(data=np.random.rand(5),name='rand_num')
# Series 객체도 (데이터프레임의 컬럼처럼) 값들의 이름을 설정할 수 있음.
s

,rand_num
0,0.969585
1,0.775133
2,0.939499
3,0.894827
4,0.597900


In [60]:
type(s)

pandas.core.series.Series

In [61]:
s.index # Series 객체가 가지고 있는 index 속성

RangeIndex(start=0, stop=5, step=1)

In [62]:
s.values # Series 객체가 가지고 있는 values 속성 >> 값들을 아이템으로 갖는 1차원 ndarray(배열)

array([0.7066256 , 0.07737764, 0.11767734, 0.82836582, 0.25211019])

In [64]:
s.loc[0] # 인덱스 0번 위치에 값

np.float64(0.7066256023012184)

In [176]:
s

,rand_num
0,0.969585
1,0.775133
2,0.939499
3,0.894827
4,0.597900


In [177]:
s.loc[[0,4]]  # 인덱스 0,4 위치의 값들 fancy

,rand_num
0,0.969585
4,0.597900


In [63]:
# s.values[0]
# s.values[-1]
# s.iloc[-1]
# s.iloc[0]
s.iloc[0:2]

,rand_num
0,0.706626
1,0.077378


In [15]:
# s.loc[-1] # 음수인덱스부재
s.loc[0:2]

,rand_num
0,0.890463
1,0.070199
2,0.626803


In [178]:
s=pd.Series(data=np.random.randint(100,size=5),name='score',index=['scott','allen','king','홍길동','오쌤'])
s

,score
scott,47
allen,14
king,71
홍길동,77
오쌤,86


In [69]:
s.index

Index(['scott', 'allen', 'king', '홍길동', '오쌤'], dtype='object')

In [70]:
s.values

array([47, 88, 97, 99, 42])

In [20]:
s.iloc[-1]

np.int64(65)

In [179]:
# s.loc[-1]
# s.loc['오쌤']
s.loc['scott':'king']

,score
scott,47
allen,14
king,71


In [26]:
s.index.nlevels # index의 레벨(계층) 개수

1

In [71]:
s.loc['홍길동'] # 해당 인덱스의 값 1개

np.int64(99)

In [72]:
s.loc[['scott','홍길동']]  # 해당 인덱스들의 값들 fancy

,score
scott,47
홍길동,99


## 계층적 인덱스(hierachical index), multi-level index

In [180]:
s=pd.Series(data=np.random.randint(100,size=6),name='score',
            index=[['m','m','m','f','f','f'],['a','b','c','a','b','c']])
s

m  a    61
   b    39
   c    84
f  a    79
   b    81
   c    52
Name: score, dtype: int64

In [74]:
s.values # 1차원 배열(ndarray)

array([91, 65, 66, 95, 81, 68])

In [75]:
s.index # MultiIndex - 튜플들을 아이템으로 갖는 배열

MultiIndex([('m', 'a'),
            ('m', 'b'),
            ('m', 'c'),
            ('f', 'a'),
            ('f', 'b'),
            ('f', 'c')],
           )

In [76]:
s.index.nlevels # nlevels 계층이 2개

2

In [77]:
# s.iloc[0]
s.iloc[-1]

np.int64(68)

### Multi-level index에서 indexing, slicing

nlevels(인덱스의 계층 개수)가 2개 이상인 multi-level 인덱스를 loc 속성에서 사용할 때,

*   첫번째 계층의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층의 인덱스만 가지고는 indexing과 slicing을 할 수 없다.
*   튜플 형태의 인덱스로 indexing/slicing을 할 수 있음.


In [78]:
s

m  a    91
   b    65
   c    66
f  a    95
   b    81
   c    68
Name: score, dtype: int64

In [79]:
s.loc['m'] # 첫번째 계층(level)의 인덱스로 indexing.

,score
a,91
b,65
c,66


In [51]:
s.loc['f']

,score
a,40
b,80
c,94


In [54]:
# s.loc['a'] # 이 방법은 가장 바깥에것(1레벨)만 찾을수있다 레벨 1  abc는 레벨 2 //  KeyError-'a'는 첫번째 계층(level)의 인덱스가 아니기 때문이다.
s.loc[('m','a')] #튜플 형태의 인덱스를 사용한 indexing.

np.int64(91)

In [80]:
s.loc[[('m','a'),('f','a')]]    # loc인덱스 > 리스트 > 인덱스 fancy

,,score
m,a,91
f,a,95


In [81]:
s_idx_sorted=s.sort_index()
s_idx_sorted

f  a    95
   b    81
   c    68
m  a    91
   b    65
   c    66
Name: score, dtype: int64

In [82]:
s_idx_sorted.loc['f':'m'] # 정렬되니까 된다  slicing 은 인덱스들이 정렬된 상태일 때 가능한것

f  a    95
   b    81
   c    68
m  a    91
   b    65
   c    66
Name: score, dtype: int64

In [83]:
s_idx_sorted.loc[('f','a'):('m','a')]

f  a    95
   b    81
   c    68
m  a    91
Name: score, dtype: int64

*   `pd.Series.sort_index()`: 인덱스를 정렬(한 새로운 Series 객체를 리턴. )
*   `pd.Series.sort_values()`: 값들을 정렬
*   `inplace` 파라미터:
      *   `inplace=True`: 원본 Series를 정렬된 상태로 변경.
      *   `inplace=False`: 원본은 수정되지 않고, 정렬된 새로운 Series를 객체를 리턴. 기본값은 False다

In [86]:
np.random.seed(42)
s= pd.Series(data=np.random.rand(5), index=['b','a','z','d','c'])
s

,0
b,0.374540
a,0.950714
z,0.731994
d,0.598658
c,0.156019


In [87]:
s.sort_values() # 값 정렬 inplace = False 기본값

,0
c,0.156019
b,0.374540
d,0.598658
z,0.731994
a,0.950714


In [88]:
s # 원래 순서로

,0
b,0.374540
a,0.950714
z,0.731994
d,0.598658
c,0.156019


In [89]:
s.sort_values(inplace=True) # inplace=True 원본변경, 리턴값은 없음
s

,0
c,0.156019
b,0.374540
d,0.598658
z,0.731994
a,0.950714


In [90]:
s # 원본 Series가 값들 오름차순 정렬된 상태

,0
c,0.156019
b,0.374540
d,0.598658
z,0.731994
a,0.950714


In [91]:
s.sort_index() # inplace=False: 기본값. 인덱스들이 정렬된 Series를 리턴

,0
a,0.950714
b,0.374540
c,0.156019
d,0.598658
z,0.731994


In [93]:
s # 원본은 변경 없음

,0
c,0.156019
b,0.374540
d,0.598658
z,0.731994
a,0.950714


In [94]:
s.sort_index(inplace=True) # inplace=True 원본 Series의 인덱스를 정렬. 리턴 값은 없음.

In [95]:
s

,0
a,0.950714
b,0.374540
c,0.156019
d,0.598658
z,0.731994


## index swapping

multi-level index에서 인덱스의 레벨을 바꿈.

In [99]:
np.random.seed(42)
s= pd.Series(data=np.random.randint(100,size=6),index=[['m']*3+['f']*3,['a','b','c']*2])
s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [102]:
s.swaplevel() # 레벨1 과 레벨2 가 바뀜    //copy=True: 기본값.원본은 변경은 없다. copy(X)// inplace=False같은개념

,,0
a,m,51
b,m,92
c,m,14
a,f,71
b,f,60
c,f,20


In [103]:
s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [100]:
# s.swaplevel(copy=False) False는 없다

,,0
a,m,51
b,m,92
c,m,14
a,f,71
b,f,60
c,f,20


In [183]:
# nlevels= 3인 인덱스를 갖는 Series
np.random.seed(42)
s=pd.Series(data=np.random.rand(6),
            index=[np.arange(1,7),
                   ['A']*3+['B']*3,
                   ['a','b','c']*2])
s

,,,0
1,A,a,0.374540
2,A,b,0.950714
3,A,c,0.731994
4,B,a,0.598658
5,B,b,0.156019
6,B,c,0.155995


In [186]:
s.index.nlevels

3

In [108]:
s.swaplevel(i=-3,j=-1) #i=-2 ,j=-1: 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

,,,0
a,A,1,0.374540
b,A,2,0.950714
c,A,3,0.731994
a,B,4,0.598658
b,B,5,0.156019
c,B,6,0.155995


In [110]:
s.swaplevel(i=0,j=1) # 첫번째 인덱스와 두번째 인덱스를 바꿈

A  1  a    0.374540
   2  b    0.950714
   3  c    0.731994
B  4  a    0.598658
   5  b    0.156019
   6  c    0.155995
dtype: float64

# DataFrame 인덱스

In [129]:
np.random.seed(42)
df= pd.DataFrame(data=np.random.randint(100,size=(6,3)),
                 columns=['total_bill','tip','size'],
                 index=[['Fri']*2+['Sat']*2+['Sun']*2,['Lunch','Dinner']*3])
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [130]:
df.values # DataFrame의 값들로 이루어진 2차원 배열(ndarray)

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99],
       [23,  2, 21],
       [52,  1, 87]])

In [131]:
df.columns # 컬럼 이름(인덱스)들로 이루어진 배열

Index(['total_bill', 'tip', 'size'], dtype='object')

In [132]:
df.index # multi-level 인덱스: 튜플들의 배열

MultiIndex([('Fri',  'Lunch'),
            ('Fri', 'Dinner'),
            ('Sat',  'Lunch'),
            ('Sat', 'Dinner'),
            ('Sun',  'Lunch'),
            ('Sun', 'Dinner')],
           )

In [133]:
df.loc['Fri']  # 첫번째 인덱스만 가지고도 indexing 가능하다

,total_bill,tip,size
Lunch,51,92,14
Dinner,71,60,20


In [134]:
df.loc[('Fri','Dinner')] # 첫번째, 두번째 계층의 인덱스들을 모두 사용한 indexing

,Fri
,Dinner
total_bill,71
tip,60
size,20


In [135]:
df.loc[['Sat','Sun']] # fancy

total_bill  tip  size
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [136]:
df.loc[[('Fri','Lunch'),('Sat','Lunch'),('Sun','Lunch')]] # fancy

,,total_bill,tip,size
Fri,Lunch,51,92,14
Sat,Lunch,82,86,74
Sun,Lunch,23,2,21


In [137]:
# df.loc['Lunch'] # Keyerror - 'Lunch'는 첫번째 계층(level)의 인덱스가 아니기 때문이다.

In [138]:
df.loc['Fri':'Sat']

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99

In [142]:
df.index.nlevels

2

In [144]:
df.swaplevel() # i=-2 ,j=-1 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

,,total_bill,tip,size
Lunch,Fri,51,92,14
Dinner,Fri,71,60,20
Lunch,Sat,82,86,74
Dinner,Sat,74,87,99
Lunch,Sun,23,2,21
Dinner,Sun,52,1,87


In [145]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [147]:
df.swaplevel().loc['Lunch'] # 이건 가능

,total_bill,tip,size
Fri,51,92,14
Sat,82,86,74
Sun,23,2,21


## DataFrame 컬럼 <---> DataFrame 인덱스

*   `pd.DataFrame.set_index()`: 데이터프레임의 컬럼(들)을 인덱스로 변환.
*   `pd.DataFrame.reset_index()`: 인덱스를 데이터프레임의 컬럼으로 변환.

In [148]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

## reset_index

In [149]:
df.reset_index() # 기본 동작: 모든 level의 인덱스를 컬럼으로 변환.

,level_0,level_1,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [150]:
# 인덱스를 컬럼으로 변환할 때 사용할 컬럼 이름들을 설정.
df.reset_index(names=['day','time'])

,day,time,total_bill,tip,size
0,Fri,Lunch,51,92,14
1,Fri,Dinner,71,60,20
2,Sat,Lunch,82,86,74
3,Sat,Dinner,74,87,99
4,Sun,Lunch,23,2,21
5,Sun,Dinner,52,1,87


In [154]:
df.reset_index(level=0, names='day') # level=0만 컬럼으로넣는다  한개일때 names=['day'], names='day' 둘다가능

,day,total_bill,tip,size
Lunch,Fri,51,92,14
Dinner,Fri,71,60,20
Lunch,Sat,82,86,74
Dinner,Sat,74,87,99
Lunch,Sun,23,2,21
Dinner,Sun,52,1,87


In [158]:
df.reset_index(level=1,names=[None,'time']) # 가장마지막 인덱스 두번째 위치에있던거라서 앞에 대체할만한 뭔가가 필요했다

,time,total_bill,tip,size
Fri,Lunch,51,92,14
Fri,Dinner,71,60,20
Sat,Lunch,82,86,74
Sat,Dinner,74,87,99
Sun,Lunch,23,2,21
Sun,Dinner,52,1,87


## `set_index`

In [167]:
exam = pd.DataFrame(data={
    'class':[1]*5+[2]*5,
    'id':np.arange(1,11),
    'math':np.random.randint(100,size=10),
    'science':np.random.randint(100,size=10)
})
exam

,class,id,math,science
0,1,1,1,80
1,1,2,83,35
2,1,3,91,49
3,1,4,59,3
4,1,5,70,1
5,2,6,43,5
6,2,7,7,53
7,2,8,46,3
8,2,9,34,53
9,2,10,77,92


In [161]:
# class = 1 인 데이터 선택
exam[exam['class']==1]

,class,id,math,science
0,1,1,61,72
1,1,2,46,38
2,1,3,61,17
3,1,4,50,3
4,1,5,54,88


In [163]:
exam_cls = exam.set_index(keys=['class']) #s 는 []인 경우가 많다
exam_cls

,id,math,science
class,,,
1,1,61,72
1,2,46,38
1,3,61,17
1,4,50,3
1,5,54,88
2,6,63,59
2,7,2,13
2,8,50,8
2,9,6,89


In [164]:
exam_cls.loc[1]

,id,math,science
class,,,
1,1,61,72
1,2,46,38
1,3,61,17
1,4,50,3
1,5,54,88


In [169]:
exam.set_index(keys=['class','id'])

math  science
class id               
1     1      1       80
      2     83       35
      3     91       49
      4     59        3
      5     70        1
2     6     43        5
      7      7       53
      8     46        3
      9     34       53
      10    77       92

In [173]:
exam.set_index(keys=['id','class']) # loc(행,열)

,2
,1
math,83
science,35
