# Ex. 1
아래의 튜플 fruits에 저장된 문자열들의 길이들을 저장하는 리스트를 만들고 출력하세요.

fruits = ('apple', 'banana', 'cherry', 'durian', 'watermellon')

In [ ]:

fruits = ('apple', 'banana', 'cherry', 'durian', 'watermellon')
fru_length=[len(x) for x in fruits] # 튜플은 XX
fru_length


[5, 6, 6, 6, 11]

In [ ]:
# lengths=[]
# for x in fruits:
#   lengths.append(len(x))
# lengths


# Ex. 2
1 이상 4 이하 범위의 정수 난수 10개를 저장하는 리스트 gender_codes를 만들고 출력하세요.
gender_codes의 값이 1 또는 3이면 'Male', 2 또는 4이면 'Female'을 저장하는 리스트 genders를 만들고 출력하세요.

In [ ]:
import random

In [ ]:
gender_codes=[random.randrange(1,5) for x in range(10)]
gender_codes

[1, 4, 2, 3, 3, 3, 4, 4, 1, 1]

In [ ]:
# gender_codes=[]

# for x in range(10):
#   gender_codes.append(random.randrange(1,5))
# gender_codes

In [ ]:
genders=['Male' if x==1 or x==3 else 'Female' for x in gender_codes]
print(genders,end='\t')

['Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male']	

In [ ]:
# genders=[]

# for x in gender_codes:
#   if x==1 or x==3:         in(1,3) =튜플
#     genders.append('Male')
#   else:
#     genders.append('Female')
# genders

# Ex. 3
아래의 두 2차원 배열 m1, m2에서 같은 인덱스의 원소들끼리 뺄셈(m1 - m2) 결과를 저장하는 리스트를 만들고 출력하세요.

m1 = [
    [1, 2, 3],
    [4, 5, 6]
]
m2 = [
    [1, 1, 1],
    [2, 2, 2]
]

In [6]:
import numpy as np

In [10]:
m1 = np.array([[1,2,3],
                [4,5,6]])
m2 = np.array([[1,1,1],
                [2,2,2]])
# m1 =(
#     [1, 2, 3],
#     [4, 5, 6]
# )
# m2 =(
#     [1, 1, 1],
#     [2, 2, 2]
# )
# m1 =(
#     [1, 2],
#     [4, 5]
# )
# m2 =(
#     [1, 1],
#     [2, 2]
# )

In [15]:
print(m1,m2)  #같은 행끼리 계산
print(m1.sum())
print(m2.sum())

[[1 2 3]
 [4 5 6]] [[1 1 1]
 [2 2 2]]
21
9


In [12]:
# result=[
#     [r1-r2 for r1,r2 in zip(row1,row2)]
#     for row1, row2 in zip(m1, m2) # 1순위  크게 [] for x in zip 이 모양이다
# ]
# result
print(m1-m2)

[[0 1 2]
 [2 3 4]]


In [ ]:
# 1차원 배열의 각 원소들끼리 뺄셈결과를 저장할 리스트
result=[]

for row1,row2 in zip(m1,m2):  # 1 크게 잡고
  row_minus=[]                # 3 작은거 넣기
  for x, y in zip(row1, row2): # 2 작은거 계산
    row_minus.append(x-y)
  result.append(row_minus)
result

#처럼 행렬 형태(2차원 리스트)를 유지하기 위해
#각 행을 계산하여 행 단위로 묶는 중간 리스트가 필요합니다.

[[0, 1, 2], [2, 3, 4]]

In [ ]:
#! result=[]
# !for r1,r2 in zip(m1,m2):
#  ! for  row1, row2 in zip(m1,m2):
#   !result.append(r1-r2)

# result

# # for row1, row2 in zip(m1, m2):
# #     temp = []
# #     for r1, r2 in zip(row1, row2):
# #         temp.append(r1 - r2)
# #     result.append(temp)


# Ex. 4

1 이상 10 이하의 정수 난수 5개를 저장하는 리스트 scores를 만들고 출력하세요.

In [ ]:
#scores=[random.randrange(1,11) for x in range(5)]
scores=[random.randrange(1,10) for x in range(5)]
#cores=[random.randrange(0,1) for x in range(5)]
print(scores)
#print(cores)

[5, 7, 7, 1, 5]


In [ ]:
num_of_items=5
scoress=[random.randrange(1,11) for x in range(num_of_items)]
scoress

[3, 2, 1, 1, 1]

In [ ]:
#반드시 반복문 또는 zip 사용

# Ex. 5

문제 4에서 만든 리스트 scores의 원소들의 합계를 계산하고 출력하세요.

In [ ]:
#s=tuple(scores)
#print(type(s))
#sum =[x+y for x,y in zip(scores,cores)]
# sums=[sum(x) for x in scores]
# sums
                      #while한번해보기
sums=scoress[0]+scoress[1]+scoress[2]+scoress[3]+scoress[4]
sums
# sum_S = sum(scores)
# sum_S
# scores=[random.randrange(1,11) for x in range(5)]

# totals=sum(scores)
# print(totals)

8

In [ ]:
# 합계함수
# totals=sum(scoress)
# print(totals)

total=0
for x in scoress:
  total +=x
total

8

# Ex. 6

문제 4에서 만든 리스트 scores의 원소들의 평균을 계산하고 출력하세요.

In [ ]:
#avg =[(x+y)/2 for x,y in zip(scores,cores)]
avgg =(scoress[0]+scoress[1]+scoress[2]+scoress[3]+scoress[4])/5
avgg

1.6

In [ ]:
mean= total / num_of_items
mean

1.6

# Ex. 7

문제 4에서 만든 리스트 scores의 원소들의 분산을 계산하고 출력하세요.

In [ ]:
var=(scoress[0]-avgg)**2+(scoress[1]-avgg)**2+(scoress[2]-avgg)**2+(scoress[3]-avgg)**2+(scoress[4]-avgg)**2
print(var)
varrr= var/5
varrr
# var= ((sums-avgg)**2)   분산= {각점수 - 평균 )^2}/5
# varr=var/5
# print(varr)

3.2


0.64

In [ ]:
variances=[]
for x in scoress:
  variances.append((x-mean)**2)
#variances

sum_of_variances=0
for x in variances:
  sum_of_variances +=x
                                      #-1? 평균이랑 같은값나올때를 대비해서 ?
varr= sum_of_variances / (num_of_items-1)
varr

0.8

In [ ]:
# # variances = []
# # for x in scores:
# #     variances.append((x - mean) ** 2)
# variances = [(x - mean) ** 2 for x in scoress]
# # print(variances)

# sum_of_variances = 0
# for x in variances:
#     sum_of_variances += x

# varr = sum_of_variances / (num_of_items - 1)
# print(varr)

# Ex. 8

문제 4에서 만든 리스트 scores의 원소들의 표준편차를 계산하고 출력하세요.

In [ ]:
#분산에 루트씌우기
sd=varr**0.5
sd

0.8944271909999159

# Ex. 9
문제 4에서 만든 리스트 scores에서 최댓값을 찾고 출력하세요

In [ ]:
#max =[max(x+y) for x,y in zip(scores,cores)]

maxx=max(scores)
maxx

7

In [ ]:
max_score = scoress[0] #리스트의 첫번째 원소 최댓값이라고 가정
for x in scores:
  if x > max_score:
    max_score=x # 돌려서 현 맥스보다 크다면 x를 맥스에 넣는다
max_score

7

# Ex. 10

문제 4에서 만든 리스트 scores에서 최솟값을 찾고 출력하세요.

In [ ]:
minn=min(scores)
minn

1

In [ ]:
min_score = scoress[0] #리스트의 첫번째 원소 최솟값이라고 가정
for x in scores:
  if x < min_score:
    min_score=x # 돌려서 현 민보다 크다면 x를 민에 넣는다
print(min_score)

1